### ISSUE TITLE
SVGO not working

### ISSUE THREAD

**Issue by julienchazal** [AlexxNB/rollup-plugin-svg-icons#2]
Hello, i've added your plugin to my `rollup.config.js` [Sapper](https://github.com/sveltejs/sapper) project.
The sprite is generated but svgo is not working: the doctype is not removed

```javascript
export default {
	client: {
		input: config.client.input(),
		output: config.client.output(),
		plugins: [
			replace({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svgicons({
				inputFolder: 'src/icons',
				output: 'src/components/sprite.svg',
				svgo: {
					removeDoctype: true
				}
			})
                 ]
           }
}
```
Can you help me please ?
Thx

**Comment by julienchazal** [comment]
@AlexxNB Can you help me please ?

**Comment by AlexxNB** [comment]
Hello! Sorry, I have no time for test it now. 
SVGO is working only with iconfiles, but not with a whole sprite. Are you sure, that doctipe wasn't removed from iconfiles?

**Comment by julienchazal** [comment]
the icon files did not have doctype in the first place
so is it possible to remove the doctype from the generated sprite ?

**Comment by AlexxNB** [comment]
I'm not shure about it. Possible, It may break the sprite in edge cases. Need to be testing additionaly.

**Comment by julienchazal** [comment]
@AlexxNB see this [answer](https://github.com/w0rm/gulp-svgstore/issues/71#issuecomment-239495726)

> there is an option for this svgstore({ inlineSvg: true })

**Comment by julienchazal** [comment]
@AlexxNB did you had the time to have a look at this ?

**Comment by AlexxNB** [comment]
@julienchazal I've remove SVGO from the package at all. Use any svgstore options (and `inline` from toString method also) as a plugin's options. Updated version on NPM already.

```javascript
/* rollup.config.js */
import svgicons from 'rollup-plugin-svg-icons'

export default {
...
  plugins: [
    svgicons({
      inputFolder: 'src/icons',  
      output: 'dist/bundle.svg',
      inline: true
    })
    ...
  ]
  ...
}
```

**Comment by julienchazal** [comment]
@AlexxNB thanks a lot !
